name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # This will trigger the workflow when tags starting with v are pushed
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Add this step to set up Docker Buildx with the proper driver
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Extract tag name if it's a tag event
    - name: Extract tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    # Prepare Docker tags
    - name: Prepare Docker tags
      id: docker_meta
      run: |
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
          # For tag events, use both tag name and 'latest'
          echo "tags=ghcr.io/${{ github.repository_owner }}/ubuntu2004-dev-env:${{ steps.tag.outputs.tag }},ghcr.io/${{ github.repository_owner }}/ubuntu2004-dev-env:latest" >> $GITHUB_OUTPUT
        else
          # For non-tag events, just use 'latest'
          echo "tags=ghcr.io/${{ github.repository_owner }}/ubuntu2004-dev-env:latest" >> $GITHUB_OUTPUT
        fi
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max